### ISSUE TITLE
Dual-licensing

### ISSUE THREAD

**Issue by tillias** [WPS/domain-story-modeler#100]
Hi lovely people, many thanks for a great tool. I'm not a big expert in GPLv3, so the question is if we can use it for commercial products without the need to showing our own code-base? We won't modify source code anyhow, just need to deploy the tool as a docker container.

**Describe the solution you'd like**
Please consider other licenses besides GPLv3

**Describe alternatives you've considered**
Event-Storming, Paper & Pencil

**Additional context**
N/A

**Comment by hschwentner** [comment]
Deploying the tool in a container is totally fine for the Gpl.

**Comment by tillias** [comment]
So if we use it without modification in-house simply to create and export images, we won't violate any licensing stuff against WPS?

**Comment by hschwentner** [comment]
Yes :-) 

See also: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**Comment by tillias** [comment]
Great, I mean I will be really happy introducing this awesome tool in my current org but we can't disclose source codes of our software simply because we deploy story modeler software and use it:
![image](https://user-images.githubusercontent.com/753889/129480809-79e3e876-6328-415e-9005-0275971001ae.png)

Not sure how to deal with it :(

**Comment by hschwentner** [comment]
You're using Linux in your org, right? Then it shouldn't be a problem to use the modeler, too. Both pieces of software share the same license and with that legal requirements.
