### ISSUE TITLE
Enable drag in replay

### ISSUE THREAD

**Issue by hctsaik** [WPS/domain-story-modeler#116]
We are use replay function to demonstrate our analysis result to user. However, if the figure is too big that we can't drag the canvas to show next activity.
If possible, may you help to evaluate the drag canvas function in the replay mode. It is really help us, thanks.

**Comment by hofstef** [comment]
Hi, this should already work - please see: https://egon.io/howto#replay

**Comment by hctsaik** [comment]
Wow, It is perfect!! thanks for your reply!!
