### ISSUE TITLE
Change current arrow color or style in replay mode

### ISSUE THREAD

**Issue by hctsaik** [WPS/domain-story-modeler#117]
The arrow is get bold In current activity. However, it is not clear to show if the figure is big.

We sometimes need to use mouse to notify user where is the next arrow or activity. May we have an option to change the style to customize the user experience, thanks

**Comment by hofstef** [comment]
I think that #56 addresses the same problem, but with a different solution (scroll to next activity automatically). I therefore mark this issue as a duplicate and close it. If I am mistaken, please reopen it with additional information.

**Comment by hctsaik** [comment]
I thought it is not the same, because if the figure in one screen but many components. We need to use mouse to point out which component is the current component. (If figure is not big than one screen, the focus not switch to current component. We rely on the bold line to find which is current component. However if it's color is more red or blue... It could help user to find it more easily)

Many thanks for your help
