### ISSUE TITLE
Draw sequence number at start of activity arrow

### ISSUE THREAD

**Issue by hschwentner** [WPS/domain-story-modeler#131]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. e.g: I'm always frustrated when...]

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

**Additional context**
[Add any other context or screenshots about the feature request here.]

**Comment by AlexanderZellober** [comment]
With Domainstories as seen in some of the examples that have many Activities fromt he same Actor, the AcitvityNumbers overlapp. Due to this, we will not do this at this time.
