### ISSUE TITLE
use outline icons instead of solid icons in palette and context pad

### ISSUE THREAD

**Issue by hofstef** [WPS/domain-story-modeler#2]
The modeler uses the _outline_ version of Google's Material icons,. However, in the context pad and in the palette, _solid_ icons are used instead. 
The icons should be unified. _Outline_ is the style of choice because it is more printer friendly.

**Comment by hofstef** [comment]
The icons for the palette and the context pad are defined in a font file that only contains solid icons. Google has not updated the font in years. 
Alternatives: 
- an alternative icon set that comes with a font (fontawesome?)
- make our own font with the icons that we need
- use svg instead of fonts; however, this breakes highlighting in the context pad.

**Comment by AlexanderZellober** [comment]
Found a way to use svg that does not break highlighting in the contextPad.
