### ISSUE TITLE
Need a way to model assumptions

### ISSUE THREAD

**Issue by sherl0cks** [WPS/domain-story-modeler#21]
It would be nice if the modeler had a way to captured assumptions in the tool

**Comment by hofstef** [comment]
So far I have recommended using the "description" (under the title) for capturing assumptions, possible variations, etc. You can use line breaks (ctrl+enter or alt+enter) for structuring the description. What I frequently do is something like that:

assumptions: <...>
other scenarios: <...>

The reason for not providing several text fields is simply that we do not want to impose too much structure. A general purpose text field gives users more freedom to capture the information they think is necessary. Does that make sense to you?

**Comment by sherl0cks** [comment]
Did not notice that feature @hofstef , thanks!
