### ISSUE TITLE
export as png or jpg

### ISSUE THREAD

**Issue by hofstef** [WPS/domain-story-modeler#26]
In addition to the svg export, a direct export to png or jpg would be useful because these file formats are often easier to share and distribute.

**Comment by Mephisztoe** [comment]
I copy that. Because I'd like to embedd domain story models to an arc42-based architecture documentation hosted as Wiki directly within Azure DevOps, an image format such as png would be of great use. Microsoft's standard implementation of markdown doesn't support embedding SVGs unfortunately.
