### ISSUE TITLE
Text annotations don't show up.

### ISSUE THREAD

**Issue by dietzma** [WPS/domain-story-modeler#27]
In Chrome Version 70.0.3538.102 text is not displayed and looks like an empty annotation box.

**Comment by hofstef** [comment]
Hi, i cannot reproduce the problem. Could you please provide a .dst and a picture that illustrates the problem?

**Comment by dietzma** [comment]
All the .dst are working now. I cannot reproduce it neither. I keep try to break it again within the next days.
