### ISSUE TITLE
Parallel steps 

### ISSUE THREAD

**Issue by dietzma** [WPS/domain-story-modeler#28]
Could find the feature, but seems that parallel steps are missing.

**Comment by hofstef** [comment]
Hi, you mean to allow the same activity number more than once so that the numbers are in a increasing monotonic sequence (rather than a  strictly increasing monotonic sequence)?
Using the same number several times would mean that these activities happen in parallel or in an arbitrary order, right?

**Comment by AlexanderZellober** [comment]
TODO: A test for the replay needs to be fixed.

**Comment by AlexanderZellober** [comment]
To be tested on FeatureTest-Branch
