### ISSUE TITLE
colored icons

### ISSUE THREAD

**Issue by hofstef** [WPS/domain-story-modeler#34]
**Is your feature request related to a problem? Please describe.**
Let the user change the color of a work object or actor, e.g. to express org. units, to distinguish digital and analog work objects etc.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Could be conflicting with #35 and #33

**Comment by AlexanderZellober** [comment]
To be tested on FeatureTest-Branch
