### ISSUE TITLE
SVG does not contain Arrowheads

### ISSUE THREAD

**Issue by nikeee** [WPS/domain-story-modeler#41]
**Describe the bug**
When the SVG is opened in an image viewer or GIMP, there are no arrowheads.
It seems that it only works when the SVG is opened in a browser (Chrome or Firefox). This also affects SVGs that are rendered in Latex documents, both on Windows and Linux.

**To Reproduce**
1. Draw anything
2. Export as SVG
3. Open the image in something different than a browser.
4. See no arrowheads

**Expected behavior**
The arrowheads shoudl be rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/4068864/52506701-a2cc8000-2bef-11e9-84bb-5ea6fccb400e.png)

**Desktop:**
 - Modeler Version: current master and https://www.wps.de/modeler
 - Browser: Firefox 65, 64 bit
 - OS: Ubuntu 18.10 and Windows 10.

Is there any workaround?

**Comment by hofstef** [comment]
Hi, the only workaround I can think of is to make a screenshot of the modeler (which is, by the way, also the workaround I use for exporting stories as png oder jpg). We will take a look at the issue.
FYI: The next modeler version will be able to export to SVG and PNG.

**Comment by hofstef** [comment]
The arrows make use of the SVG "marker" feature. We checked the modeler's SVG implementation and it conforms to the SVG 1.1 standard. Gimp uses a slightly different representation for vector graphics (https://docs.gimp.org/2.8/en/gimp-using-paths-and-svg.html) which could explain the problem. 
We suspect a similar issue with using the modeler's SVG in LaTex. Maybe the PDF converter cannot handle the "marker" feature properly.

If the "marker" feature is the reason for the problems, solving this issue would require writing a customized SVG exporter that does not use markers. We are sorry but that is not on our roadmap. I don't think there is anything we can do to resolve this issue, so I will close it.
