### ISSUE TITLE
Change arrow animation order

### ISSUE THREAD

**Issue by Richargh** [WPS/domain-story-modeler#43]
**Is your feature request related to a problem? Please describe.**
Currently the animation order [the little number (1) or (2) next to an arrow] is fixed based on when I added it. The problem is that new arrows are discovered during the modeling phase, that might have an order number that is lower than the already existing arrows.

**Describe the solution you'd like**
I would like to be able to reorder arrows in the animation.

**Describe alternatives you've considered**
I would like to be able to edit the arrow order label.

**Additional context**
None

**Comment by hofstef** [comment]
Hi, if I understand you correctly, this is already possible. Please check this snippet from the [Readme](https://github.com/WPS/domain-story-modeler/blob/master/)

Naming and Numbering of Activities
Activities are depicted as arrows. Double click on an arrow to edit the activity's name. If you model an activity between an actor (person, people and system) and a workobject (folder, call, email, conversation, information) it will be numbered automatically. By double clicking on the arrow you can manually change the number. All other numbers are adjusted automatically.

**Comment by Richargh** [comment]
Yes you are right, that is exactly what I wanted. I made the mistake of only clicking on the label and not trying to double-click the arrow.

Then I'd like to modify my feature request: double-clicking the number label has the same effect as double-clicking the arrow. :)

**Comment by hofstef** [comment]
I opened a new issue for the feature request, see #45  
Feel free to comment.
