### ISSUE TITLE
edit activity by double clicking on activity label or number

### ISSUE THREAD

**Issue by hofstef** [WPS/domain-story-modeler#45]
**Is your feature request related to a problem? Please describe.**
Some users expect the activity label and/or number to be editable. After all, a double click on the label of an actor or work object lets you edit its label. Activities behave differently.
Also, double-clicking on the line of the arrow is not that easy.

**Describe the solution you'd like**
If I doube-click on the label of an activity, I can edit the label. 
If I doube-click on the number of an activity, I can edit the number. 

**Describe alternatives you've considered**
Inline-editing after double click would we closest to the behavior that users expect. But if I remember correctly, we have already looked into that and it was not so easy to get it to work with a label and a number. 
For me, a viable alternative would be that a double-click on either the label or the number opens the same popup that we currently show when clicking on the arrow.

**Comment by Richargh** [comment]
I just had a chance to check it out. Very nice and I think quite intuitive. Thanks :)

**Comment by hofstef** [comment]
> I just had a chance to check it out. Very nice and I think quite intuitive. Thanks :)

I never thought of this feature until you asked for it; now I use it all the time :-)
