### ISSUE TITLE
dst files created with version 0.4.0 do not show up in 0.5.0 modeler

### ISSUE THREAD

**Issue by hemzet** [WPS/domain-story-modeler#48]
Hi,
Trying to import a 0.4.0 version dst-file into the new 0.5.0 online modeler does not show any of the created icons and processes. The modeler screen remains blank. However, the name list of all entities is imported and can be modified.
This affects all major browsers (IE, Firefox, Chrome). That said, Chrome at least gives a hint regarding an incompatible version when importing the yesterdays created file.
Hope time was not wasted and import can be made compatible. Thanks
Regards

**Comment by AlexanderZellober** [comment]
Hello,
I've checked version compatibility with our example stories, which were created with version 0.4.0, and they are working fine.
Have you checked wheter the svg or png export are showing your story? If so, the story might be imported correctly, but starts somewhere further away from the (0,0)-coordinates of the canvas.
Otherwise could you provide us with your dst-file? If you need to anonymize it, you can edit it as an xml-file.

**Comment by hemzet** [comment]
Alex,
Thanks for letting know. I tried importing the models a couple of times. I was able to import some of the files after I reloaded the page. However, it seemed to not work to load a file into when an existing project was active (so the web site not reset).
Anyway, after scrolling some minutes through the blank screen, even to the left and to the right, I was able to see the diagrams. So all good now.
Just out of curiosity, is there any quicker way to find the diagram than scrolling blind? Thanks

**Comment by AlexanderZellober** [comment]
Currently there is no simple way to do this. I've added a feature request to move the domain-Story close to the canvas origin #49.
For now, you could check in the html to find a general direction, in which your story lies.

When inspecting the page traverse the tree down to the first svg-tag.
Under this, there is a viewport element with two children. 
In the layer-base child, all story elements are listed with the djs-group class. Their child should have a transform attribute which defines the position on the canvas.
There are two forms the transform can take, wich have a different amount of numbers in them. The last two are always the x- and y-coordinates of this element. A positive number means it goes to the right or downwards, and a negative means left or upwards.

**Comment by hofstef** [comment]
Since there is a workaround I will close this issue. We will prevent this behaviour from happening in the next release, see #49
