### ISSUE TITLE
Upload custom icons with filename containing special characters

### ISSUE THREAD

**Issue by kaischi69** [WPS/domain-story-modeler#65]
When I upload a custom icon which has the following filename syntax, the application crashes. You got an empty model and cannot safe anything. The only fix is to delete all cached browser data.

Filename syntax: 24px (3).svg

Chrome Version 76.0.3809.100 (Offizieller Build) (64-Bit)

**Comment by hofstef** [comment]
This issue will be solved with #62 . Spaces will be replaced with underscore _
