### ISSUE TITLE
custom icons?

### ISSUE THREAD

**Issue by hofstef** [WPS/domain-story-modeler#7]
We want to brainstorm and compare different ways to customize icons.

**Comment by hofstef** [comment]
Basically, we can distinguish two kinds of customization:
1.) add/replace icons in the pallet and context pad:
- Idea: make the whole Google Material icon set available in the modeler and let the user configure which icon should appear in the pallet and the context pad
- Idea: describe how to fork and customize the modeler (probably needs refactoring to make customization easier)

2.) change icons for an instance of a work object
- Idea: import SVG from a local drive. Seems technically viable.
- Idea: let the user change the color of a work object

**Comment by hofstef** [comment]
Another idea: customizable color themes, e.g. to distinguish actors from work objects

**Comment by sherl0cks** [comment]
I'd vote for 1.a, but keep the base icon set as is, allowing end users to grow it if needed. That will likely result in scenarios where the palette becomes too big or unmanageable, but I think that might be a desirable problem to have and one to solve once we have it.

**Comment by hofstef** [comment]
I have split this issue. See #32 #33 #34 #35
