### ISSUE TITLE
Dynamically create a picture from file

### ISSUE THREAD

**Issue by Slohrsh** [WPS/domain-story-modeler#72]
It would be great if it would be possible to somehow create a picture from a file like for example with planttext (https://www.planttext.com/?).
That would help a lot for documentation that is automatically created with e.g. grade, maven.

**Comment by hofstef** [comment]
Seems like someone else had the same idea and built a tool for it: [Domain Storytelling with PlantUML](https://github.com/johthor/DomainStory-PlantUML ).
The Domain Story Modeler is meant for interactive modeling in workshops with domain experts. Generating documentation is a use case for Domain Storytellig that requires different tooling, imho. I don't think that we will provide something similar to  PlantUML in the foreseable future, hence I will close the ticket.
