### ISSUE TITLE
Draw groups as last step in replay

### ISSUE THREAD

**Issue by hschwentner** [WPS/domain-story-modeler#77]
When stepping through the replay the groups are shown all the time. I think it would be better to hide them and only show them as the last step. This reflects the typical way we use them: model the process first and then find boundaries.

Maybe it would be even better to show each group/context as its own step in replay.

**Comment by hofstef** [comment]
Determining the sequence in which the groups should appear during replay proved tricky. So we decided to show all groups as the last step of a replay, like Henning originally suggested. That means: If a story has n activities and contains one or more groups, a replay will take n+1 steps.
