### ISSUE TITLE
When deleting a group ask if contents should be deleted, too

### ISSUE THREAD

**Issue by hschwentner** [WPS/domain-story-modeler#78]
**Is your feature request related to a problem? Please describe.**
When a group is deleted everything that it contains well also be deleted. While this behavior is what the user intends in some cases, in most cases they want only the frame to be deleted and not its contents.

**Describe the solution you'd like**
When the trashcan icon on a group is clicked ask the user "Do you want to also delete the contents?" and act accordingly.

**Describe alternatives you've considered**
Another way would be to have to trashcan icons:
- one that deletes only the frame of a group
- another one that deletes also the contents.

**Comment by hofstef** [comment]
With v1.2.1, we changed the beviour for deleting groups: Only the group is deleted, not the contents. 
This is not exactly what was proposed in this issue, but 1.) it was easier to implement and 2.) deleting a group and its contents can easily be done using the "lasso" tool (ctrl+L) for selecting multiple elements and then deleting them with the DEL od backspace key.
