### ISSUE TITLE
Allow copy/paste

### ISSUE THREAD

**Issue by brampeirs** [WPS/domain-story-modeler#88]
**Is your feature request related to a problem? Please describe.**
Today I cannot copy paste elements.

**Describe the solution you'd like**
I would like to be able to copy/paste flows.

**Describe alternatives you've considered**
none

**Additional context**
/

**Comment by hofstef** [comment]
v1.2.1 (re-)introduces copy/paste:

- For work objects and actors, copy/paste works as expected.
- If a whole sentence (actor + activity + work object) is copied, the new sentence is assigned a new sequence number (i.e., increasing the previously highest sequence number. 
- If several sentences are copied, the are all assigned the same new sequencte number. This means you will have to adapt the numbers manually as needed. We think this is a reasonable default behaviour that also covers edge cases (e.g. copying sentences with non-consecutive numbering).
