### ISSUE TITLE
Activities are not imported

### ISSUE THREAD

**Issue by ramnes** [WPS/domain-story-modeler#91]
**Describe the bug**
Exporting and re-importing a story makes all activities disappear.

**To Reproduce**
Download [this story](https://github.com/WPS/domain-story-modeler/files/6272954/bug.dst.txt), remove the .txt suffix (that's here to make GitHub happy), and import it.

**Expected behavior**
There should be a "buys" activity between the user and the ticket.

**Screenshots**
![bug_2021-04-07](https://user-images.githubusercontent.com/835072/113897619-5418d180-97cb-11eb-80f9-762c1127d6e7.png)

**Desktop (please complete the following information):**
 - Modeler Version: 00dd85a
 - Browser: Google Chrome 88.0.4324.182 
 - OS: Linux

**Additional context**
Importing in the online version works, minus the version mismatch warning popup, so I guess it's a bug that got introduced between v1.1.0 and the current version.

**Comment by ramnes** [comment]
Works with v1.2.0 as well.

**Comment by hofstef** [comment]
This bug was only present in trunk (v1.2.1-dev), not in any released version. Fixed with v1.2.1
