### ISSUE TITLE
PNG is not exported correctly / corrupted

### ISSUE THREAD

**Issue by max-white** [WPS/domain-story-modeler#92]
**Describe the bug**
When i export the story as a PNG and view the exported PNG in the Windows 10 picture viewer
and copy the picture to the OS clipboard (CTRL+C) and afterwards paste it into Zoom, the picture
is corrupted.

**To Reproduce**
1. Export PNG from Domain Story
2. Open Photos (Windows 10) with picture
3. Press CTRL+C
4. CTRL+V in Zoom-Chatbox

**Expected behavior**
PNG is exported correctly and can be pasted easily to other applications

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4263821/116282667-53041000-a78b-11eb-85d4-aa8623864200.png)

**Desktop (please complete the following information):**
 - Modeler Version: v1.2.0
 - Browser: Chrome  90.0.4430.85
 - OS: Windows 10

**Comment by AlexanderZellober** [comment]
Currently the PNG is exported with a transparent background, this was fixed with https://github.com/WPS/domain-story-modeler/pull/90

**Comment by hofstef** [comment]
With v1.2.1, PNG will be exported with white background instead of transparent because this seems to be a more reasonable default for the majority of users.
