### ISSUE TITLE
List in the Context Menu is not displaying all Work Objects

### ISSUE THREAD

**Issue by max-white** [WPS/domain-story-modeler#93]
**Describe the bug**
List in the context menu is not displaying all work objects when having alot of work objects
and i want to change the icon of the work object.

**To Reproduce**
1. Add atleast 26 work objects
2. change existing work objects to the last work object

**Expected behavior**
last work object should be selectable

**Desktop (please complete the following information):**
 - Modeler Version: 1.2.0
 - Browser: Chrome Version 90.0.4430.93
 - OS: Windows 10

**Comment by hofstef** [comment]
I see the problem and ideally it should be fixed. However, I usually advise people to keep the pictographic language concise. The more icons you use, the harder it will be to recognize them and remember what they mean. For example, I use the "document" icon for all kinds of documents; only if one document is of significant importance, I will introduce a specific icon for that. Usually, I get by with a dozen or so icons.

Maybe there is another reason why you want to use many icons: If you, as the moderator, often switch between domains, I would recommend to build several "domain configurations" (and export each as .domain file for sharing/reuse), one for each (sub-)domain.

**Comment by hofstef** [comment]
v.1.2.1 intorduces a scrollable context pad with enough space for... a lot of icons. However, proceed with caution ;-)
