### ISSUE TITLE
Cannot scroll the screen in replay mode

### ISSUE THREAD

**Issue by apae89** [WPS/domain-story-modeler#95]
Hi,

First of all, thanks for your great work!

**Describe the bug**
When I start viewing a story in replay mode, I cannot scroll the screen using the mouse, like in edit mode. This is pretty annoying if a story does not fit the screen. I can only zoom out and zoom into the desired story detail using STRG + mouse wheel.

**To Reproduce**
1. Create a story
2. Click on "Replay mode"
3.  Press and hold down the mouse and try to scroll the screen 

**Expected behavior**
Scroll the screen like in edit mode using the 3. step described above.

**Desktop (please complete the following information):**
 - Modeler Version: the deployed web version -> 1.2.1? But I see the same effect using older versions
 - Browser: Chrome 90.0.4430.212 
 - OS: Windows 10

**Comment by hofstef** [comment]
Hi Andreas, you can scroll when in replay mode. This was not described well in the readme. I updated it as follows:

Editing is disabled in replay mode, but you can zoom (ctrl + mouse wheel up and down), scroll up/down (mouse wheel up and down), and scroll left/right (shift + mouse wheel up and down). You can also move the modeling canvas by keeping the space bar pressed and move the mouse around.

**Comment by apae89** [comment]
Hi Stefan,
Thank you for your quick response. 
Scrolling left and right was not intuitive for me. Is there a particular reason, why the scrolling was implemented differently to the edit mode? Is it maybe possible to adapt the scrolling...?
From my perspective, it's more comfortable if scrolling would be implemented equal to edit mode in addition to the more consistent feeling from UX perspective.
