### ISSUE TITLE
Invalid .domain file generated or import broken

### ISSUE THREAD

**Issue by sniechzial** [WPS/domain-story-modeler#97]
I've configured a set of Actors and WorkObjects and exported it to a custom `.domain` file. Importing the file again leads to an empty set of WorkObjects and Actors and to an exception.

In the screencast, the list seems to be correctly loaded but looking at the Local Storage, `customConfig` is empty and returning to the main screen gives an empty toolbox.

It does not contain any custom uploaded icons.

### Attachments 
- [the domain file](https://github.com/WPS/domain-story-modeler/files/6700091/reasy.zip)

### Screencast
https://user-images.githubusercontent.com/1297938/123059689-5114a100-d40a-11eb-9e51-8a2a012e5c2f.mp4

**Comment by AlexanderZellober** [comment]
There seems to be a problem with Iconnames, that include other iconnames, that are selected. In this case key(selected) and keyboard (unselected).

**Comment by sniechzial** [comment]
Wow. Thank you for the quick fix @AlexanderZellober :)

**Comment by hofstef** [comment]
Fixed with v1.3.0
