### ISSUE TITLE
Save DST-Files and share them via link 

### ISSUE THREAD

**Issue by JoThomsen** [WPS/domain-story-modeler#99]
Problem:
We often have the problem that we make Domain Story Tellings with the tool and then have to upload the DST files and a picture of them in a complicated way to our wiki or to the project page.

Solution:
What I would like to see is a save button that allows me to save the DSTs directly on the server. Then I can share the DSTs with colleagues via e.g. a link (see e.g. https://play.openpolicyagent.org/p/EpKRvaVGPG). 
It would also be cool if a DST snippet could be displayed as a link preview so that I can embed it directly in my project pages like a Miro board, for example.

**Comment by hofstef** [comment]
Hi, other users have requested similar features, like #68 and #84 so I am labeling this as 'duplicate'. However, I will keep this issue open as you brought up new ideas:
- we could build our own infrastructure for sharing files (currently, Domain Story Modeler runs in the browser without a server)
-  generate preview-snippet when sharing file
